apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
  labels:
    app: python-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: vyshakprojects/demo-image-test:a634b2c7d1e713d82e730b49401d7dce562c98ed
        ports:
        - containerPort: 8000  # Update with the port your app listens on
        env:
        - name: ENV_VAR_NAME  # Add any environment variables if needed
          value: "your_value"
