apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  labels:
    app: python-app
spec:
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 80          # Port on which the service is exposed
      targetPort: 8000   # Port on the container where the app listens
  type: ClusterIP
