name: Python application

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Login to Docker Hub
      - name: login to docker hub
        id: docker-hub
        env:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
        run: |
          docker login -u $username -p $password 

      # Build the Docker image
      - name: build the docker image
        id: build-docker-image
        run: |
          ls -la 
          docker build . -f Dockerfile -t ${{secrets.DOCKERHUB_USERNAME}}/demo-image-test:${{ github.sha }}

      # Push the Docker image
      - name: push the docker image
        id: push-docker-image
        run: |
          docker push ${{secrets.DOCKERHUB_USERNAME}}/demo-image-test:${{ github.sha }}

      - name: Checkout feature-branch
        uses: actions/checkout@v2
        with:
          ref: main

      # (Optional) Commit and push changes to deployment.yaml if you want
      - name: Commit and push changes to deployment.yaml
        run: |
          git config --global user.name "vyshakprojects"
          git config --global user.email "vyshakm117@gmail.com"

      # Update the Helm chart with the new commit SHA
      - name: Update Helm deployment.yaml with new SHA
        run: |
          SHA=${{ github.sha }}
          echo "Updating Helm chart deployment.yaml with image tag ${SHA}"

          # Update the image in deployment.yaml with the new SHA
          sed -i "s|vyshakprojects/demo-image-test:.*|vyshakprojects/demo-image-test:${SHA}|" deployment/deployment.yaml

          # Optionally, print out the updated file to verify the change
          cat deployment/deployment.yaml
        
      # (Optional) Commit and push changes to deployment.yaml if you want
      - name: Commit and push changes to deployment.yaml
        run: |
          # Optionally, print out the updated file to verify the change
          cat deployment/deployment.yaml

          git add deployment/deployment.yaml
          git commit -m "Update image tag in Helm chart to ${SHA}"
          git push origin main