name: Python application

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write  # Ensure GitHub Actions has write access to the repository contents

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Login to Docker Hub
      - name: login to docker hub
        id: docker-hub
        env:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          docker login -u $username -p $password 

      # Build the Docker image
      - name: build the docker image
        id: build-docker-image
        run: |
          ls -la 
          docker build . -f Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/demo-image-test:${{ github.sha }}

      # Push the Docker image
      - name: push the docker image
        id: push-docker-image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/demo-image-test:${{ github.sha }}

      # Checkout feature-branch
      - name: Checkout feature-branch
        uses: actions/checkout@v2
        with:
          ref: main
          
      # Update the Helm chart with the new commit SHA
      - name: Update Helm deployment.yaml with new SHA
        run: |
          SHA=${{ github.sha }}
          echo "Updating Helm chart deployment.yaml with image tag ${SHA}"

          # Update the image in deployment.yaml with the new SHA
          sed -i "s|vyshakprojects/demo-image-test:.*|vyshakprojects/demo-image-test:${SHA}|" deployment/deployment.yaml

          # Optionally, print out the updated file to verify the change
          cat deployment/deployment.yaml
        
      # Commit and push changes to deployment.yaml using a personal access token (PAT)
      - name: Commit and push changes to deployment.yaml
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Reference the secret with your PAT
        run: |
          git config --global user.name "vyshakprojects"
          git config --global user.email "vyshakm117@gmail.com"
          
          # Set up the git remote URL to use the token for authentication
          git remote set-url origin https://github.com/${{ github.repository }}.git

          git add deployment/deployment.yaml
          git commit -m "Update image tag in Helm chart to ${SHA}"
          
          # Push using the personal access token
          git push https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main